server:
    port: 8080
    servlet:
        context-path: /

spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB
    # virtual threads can be enabled only on Spring Boot 3.2+
    threads:
        virtual:
            enabled: true
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
    datasource:
        url: ${database_url}
        username: ${database_username}
        password: ${database_password}
        driverClassName: org.postgresql.Driver
    jpa:
        open-in-view: false
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    level:
        ROOT: INFO
        logging.level.org.hibernate.SQL: INFO
